-- MySQL Script generated by MySQL Workbench
-- Tue Sep 10 10:13:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecommerce` ;

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8mb4 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`User` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(25) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `created_at` DATETIME GENERATED ALWAYS AS (NOW()) VIRTUAL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUsers_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Category` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME GENERATED ALWAYS AS (NOW()) VIRTUAL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `category_name_UNIQUE` (`category_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Order_Table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Order_Table` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Order_Table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `shipping_address` VARCHAR(300) NOT NULL,
  `payment_id` INT NULL,
  `order_date` DATETIME NULL DEFAULT NOW(),
  `delivery_date` DATETIME NULL,
  `order_status` VARCHAR(20) NULL DEFAULT 'Payment Pending',
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `total_amount` FLOAT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_payment_id_idx` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerce`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_id`
    FOREIGN KEY (`payment_id`)
    REFERENCES `ecommerce`.`Payment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Payment` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total_amount` FLOAT NOT NULL,
  `payment_method` VARCHAR(20) NULL,
  `payment_date` DATETIME NULL,
  `payment_status` VARCHAR(10) NOT NULL DEFAULT 'Pending',
  `order_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idPayment_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_order_id_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `ecommerce`.`Order_Table` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Product` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `product_details` VARCHAR(300) NOT NULL,
  `price` FLOAT NOT NULL,
  `quantity` INT NOT NULL,
  `category_id` INT NOT NULL,
  `created_at` DATETIME GENERATED ALWAYS AS (NOW()) VIRTUAL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `ecommerce`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Order_Details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`Order_Details` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`Order_Details` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `total_price` FLOAT GENERATED ALWAYS AS (price*quantity) VIRTUAL,
  INDEX `fk_order_id_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_id_2`
    FOREIGN KEY (`order_id`)
    REFERENCES `ecommerce`.`Order_Table` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_id_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `ecommerce`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
