-- MySQL Script generated by MySQL Workbench
-- Fri 08 Nov 2024 09:49:31 PM PKT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema job_fair
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `job_fair` ;

-- -----------------------------------------------------
-- Schema job_fair
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `job_fair` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `job_fair` ;

-- -----------------------------------------------------
-- Table `job_fair`.`Application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `job_fair`.`Application` ;

CREATE TABLE IF NOT EXISTS `job_fair`.`Application` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `job_post_id` INT NOT NULL,
  `job_seeker_id` INT NOT NULL,
  `status` ENUM('applied', 'approved', 'rejected', 'hired') NULL DEFAULT 'applied',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `job_post_id` (`job_post_id` ASC, `job_seeker_id` ASC) VISIBLE,
  INDEX `job_seeker_id` (`job_seeker_id` ASC) VISIBLE,
  CONSTRAINT `Application_ibfk_1`
    FOREIGN KEY (`job_post_id`)
    REFERENCES `job_fair`.`JobPost` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `Application_ibfk_2`
    FOREIGN KEY (`job_seeker_id`)
    REFERENCES `job_fair`.`JobSeeker` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `job_fair`.`Employer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `job_fair`.`Employer` ;

CREATE TABLE IF NOT EXISTS `job_fair`.`Employer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(255) NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_emp_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_emp_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `job_fair`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `job_fair`.`JobPost`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `job_fair`.`JobPost` ;

CREATE TABLE IF NOT EXISTS `job_fair`.`JobPost` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employer_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `skills` TEXT NULL DEFAULT NULL,
  `salary_range` VARCHAR(50) NULL DEFAULT NULL,
  `is_enabled` TINYINT(1) NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `employer_id` (`employer_id` ASC) VISIBLE,
  CONSTRAINT `JobPost_ibfk_1`
    FOREIGN KEY (`employer_id`)
    REFERENCES `job_fair`.`Employer` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `job_fair`.`JobSeeker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `job_fair`.`JobSeeker` ;

CREATE TABLE IF NOT EXISTS `job_fair`.`JobSeeker` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cv` BLOB NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_js_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_js_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `job_fair`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `job_fair`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `job_fair`.`User` ;

CREATE TABLE IF NOT EXISTS `job_fair`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `groups` ENUM('Admin', 'Employer', 'Job Seeker') NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
