# Generated by Django 5.1.2 on 2024-11-04 16:27
import datetime

from django.db import migrations

def create_through_relations(apps, schema_editor):
    Product = apps.get_model('core', 'Product')
    ProductSupplier = apps.get_model('core', 'ProductSupplier')
    for product in Product.objects.all():
        for supplier in product.supplier.all():
            ProductSupplier(
                supplier=supplier,
                product=product
                # created_at=datetime.date.today(),
                # updated_at=datetime.date.today()
            ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_productsupplier'),
    ]

    operations = [
        # migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
