# Generated by Django 5.1.2 on 2024-11-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(related_name='product_supplier', through='core.ProductSupplier', to='core.supplier'),
        ),
    ]
