# Generated by Django 5.1.2 on 2024-11-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_created_by_product_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=9)),
                ('quantity', models.PositiveIntegerField()),
                ('category', models.IntegerField()),
                ('supplier_ids', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.DateTimeField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
