-- MySQL Script generated by MySQL Workbench
-- Tue 05 Nov 2024 08:56:29 PM PKT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema blogging_app
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `blogging_app` ;

-- -----------------------------------------------------
-- Schema blogging_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blogging_app` ;
USE `blogging_app` ;

-- -----------------------------------------------------
-- Table `blogging_app`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogging_app`.`Category` ;

CREATE TABLE IF NOT EXISTS `blogging_app`.`Category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blogging_app`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogging_app`.`Comment` ;

CREATE TABLE IF NOT EXISTS `blogging_app`.`Comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `content` TEXT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `post_id` (`post_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `Comments_ibfk_1`
    FOREIGN KEY (`post_id`)
    REFERENCES `blogging_app`.`Post` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `Comments_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `blogging_app`.`User` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blogging_app`.`Like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogging_app`.`Like` ;

CREATE TABLE IF NOT EXISTS `blogging_app`.`Like` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `post_id` INT NULL DEFAULT NULL,
  `comment_id` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `post_id` (`post_id` ASC) VISIBLE,
  INDEX `comment_id` (`comment_id` ASC) VISIBLE,
  CONSTRAINT `Likes_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `blogging_app`.`User` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `Likes_ibfk_2`
    FOREIGN KEY (`post_id`)
    REFERENCES `blogging_app`.`Post` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `Likes_ibfk_3`
    FOREIGN KEY (`comment_id`)
    REFERENCES `blogging_app`.`Comment` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blogging_app`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogging_app`.`Post` ;

CREATE TABLE IF NOT EXISTS `blogging_app`.`Post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `Posts_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `blogging_app`.`User` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blogging_app`.`Post_Authors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogging_app`.`Post_Authors` ;

CREATE TABLE IF NOT EXISTS `blogging_app`.`Post_Authors` (
  `post_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`post_id`, `user_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `Post_Authors_ibfk_1`
    FOREIGN KEY (`post_id`)
    REFERENCES `blogging_app`.`Post` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `Post_Authors_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `blogging_app`.`User` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blogging_app`.`Post_Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogging_app`.`Post_Category` ;

CREATE TABLE IF NOT EXISTS `blogging_app`.`Post_Category` (
  `post_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`post_id`, `category_id`),
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `Post_Categories_ibfk_1`
    FOREIGN KEY (`post_id`)
    REFERENCES `blogging_app`.`Post` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `Post_Categories_ibfk_2`
    FOREIGN KEY (`category_id`)
    REFERENCES `blogging_app`.`Category` (`category_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blogging_app`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogging_app`.`User` ;

CREATE TABLE IF NOT EXISTS `blogging_app`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('Superuser', 'Moderator', 'Author', 'Reader') NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
