# Generated by Django 5.1.2 on 2024-11-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_productaudit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productaudit',
            old_name='category',
            new_name='category_id',
        ),
    ]
