# Generated by Django 5.1.2 on 2024-11-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_product_created_by_remove_product_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaudit',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='supplier_ids',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
